### ISSUE TITLE
Error :     paragraph = PARAGRAPH(raw=txt_para[i]) IndexError: list index out of range

### ISSUE THREAD

**Issue by Evarln** [abtExp/doccano_to_bilou#2]
As it is put in the title, I have a problem with the paragraph but I don't really understand how to fix it. Any ideas? If you need an input, I can do it.

**Comment by abtExp** [comment]
Hi @Evarln , sorry for the late reply, can you please share the structure of a sample or if possible the output from doccano which is causing this issue
