### ISSUE TITLE
Doccano to bilou for RE

### ISSUE THREAD

**Issue by Aj-232425** [abtExp/doccano_to_bilou#3]
Hi Anubhav, 
I have gone throught the script. It converts doccano jsonl output of NER to bilou format. 
I am working for relation extraction.
How can I convert jsonl of relation extraction to bilou format. Does jsonl itself be supported by Bert /BioBERT. If not so, could you please guide.
Any help will be appreciated.

**Comment by abtExp** [comment]
Hi Ajit,
I wrote that script for NER usecase and it doesn't support converting relation info jsonl to bilou.

As i don't readily work on NLP problems, I'm not sure about the training data preparation steps for bioBERT and it's architecture, so unfortunately i won't be of much help to you.

One thing you can do is research on the training pipeline of your usecase and write a custom script to convert the jsonl to the required format.

I hope you find the solution. All the best for your project.

Cheers
